name: Generate beIN EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # كل 6 ساعات

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # تثبيت Mono لتشغيل WebGrab+Plus
      - name: Install Mono
        run: |
          sudo apt update
          sudo apt install -y mono-complete

      # تشغيل WebGrab+Plus
      - name: Run WebGrab++
        run: |
          cd config
          mono WebGrab++.exe

      # نسخ guide.xml إلى مجلد output
      - name: Copy guide.xml
        run: |
          cp guide.xml ../output/guide.xml

      # Commit and push guide.xml تلقائياً
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update guide.xml"
          file_pattern: "output/guide.xml"
